//! Golden regression cases distilled from the 2026-07-16 user screenshot
//! report (64 screenshots of real category/localization mistakes across a
//! ~500-game library). Each case is a real path from the report; sibling
//! files are included per game because the family heuristics depend on
//! sibling context.
//!
//! The check mirrors the app's `combine_finding` precedence: if the rule
//! engine claims a file, its category wins; localization findings apply
//! only to files no rule claimed.
//!
//! Known limitation, deliberately NOT asserted here: per-language *game
//! data* sets that are structurally identical to localization sets
//! (Europa Universalis 4 `common\province_names\french.txt` and Paradox
//! `localisation\*_l_french.yml`, which the game loads for every language
//! at once). Distinguishing those needs per-game community rules, not a
//! heuristic — see the rules import/export design.

use gametrimmer_core::langdetect::{LangDetector, LangFinding};
use gametrimmer_core::rules::{Category, RuleEngine};
use gametrimmer_core::scanner::FileEntry;

/// Expected outcome for one path after rules + localization combine.
enum Expect {
    /// Must not be flagged by anything.
    Nothing,
    /// Must be flagged as localization with this canonical language tag.
    Loc(&'static str),
    /// Must be claimed by the rule engine with this category.
    Rule(Category),
    /// Must be flagged as localization; the exact language tag is not
    /// asserted (sibling context in the test is a subset of the real dir).
    LocAny,
}
use Expect::*;

struct Case {
    path: &'static str,
    expect: Expect,
}

fn c(path: &'static str, expect: Expect) -> Case {
    Case { path, expect }
}

/// (game name, screenshot refs, cases). Sibling rows without assertions
/// still shape the family heuristics.
fn games() -> Vec<(&'static str, Vec<Case>)> {
    vec![
        (
            "readmes-01",
            vec![
                c("Readmes\\cs_readme.txt", Rule(Category::DocsFile)),
                c("Readmes\\de_readme.txt", Rule(Category::DocsFile)),
                c("Readmes\\es-mex_readme.txt", Rule(Category::DocsFile)),
                c("Readmes\\fr-fr_readme.txt", Rule(Category::DocsFile)),
                c("Readmes\\hu_readme.txt", Rule(Category::DocsFile)),
                c("Readmes\\it_readme.txt", Rule(Category::DocsFile)),
            ],
        ),
        (
            "eula-04",
            vec![
                c("EULA_DE.DOCX", Rule(Category::DocsFile)),
                c("EULA_ES.DOCX", Rule(Category::DocsFile)),
                c("EULA_FR.DOCX", Rule(Category::DocsFile)),
                c("EULA_PL.DOCX", Rule(Category::DocsFile)),
                c("EULA_RU.DOCX", Rule(Category::DocsFile)),
            ],
        ),
        (
            "brawlhalla-02",
            vec![
                c(
                    "sprites\\AutoGenerated\\Sprites_Emoticon\\a_Flag1a_DoodleKor.png",
                    Nothing,
                ),
                c(
                    "sprites\\AutoGenerated\\Sprites_Emoticon\\a_Flag1a_DoodleMagyar.png",
                    Nothing,
                ),
                c(
                    "sprites\\AutoGenerated\\Sprites_Emoticon\\a_Flag1a_FlagCzech.png",
                    Nothing,
                ),
                c(
                    "sprites\\AutoGenerated\\Sprites_Emoticon\\a_Flag2a_MagyarPortrait.png",
                    Nothing,
                ),
                c(
                    "sprites\\AutoGenerated\\Sprites_Avatars\\a_AvatarIcon_CzechRepublic.png",
                    Nothing,
                ),
            ],
        ),
        (
            "house-flipper-03",
            vec![
                c(
                    "HouseFlipper_Data\\StreamingAssets\\aa\\StandaloneWindows64\\petsfur_assets_norwegian_furdata0_b662d221de889deb.bundle",
                    Nothing,
                ),
                c(
                    "HouseFlipper_Data\\StreamingAssets\\aa\\StandaloneWindows64\\petsfur_assets_norwegian_furdata1_5a26e8ecb4115078.bundle",
                    Nothing,
                ),
            ],
        ),
        (
            "kingmaker-05",
            vec![
                c(
                    "DigitalRewards\\Pathfinder-Kingmaker-CRPG_Pawns.pdf",
                    Rule(Category::Bonus),
                ),
                c(
                    "DigitalRewards\\Pathfinder Chris Avellone Adventure - The Puzzle Box.pdf",
                    Rule(Category::Bonus),
                ),
            ],
        ),
        (
            "eschalon-06",
            vec![
                c("Manual.pdf", Rule(Category::DocsFile)),
                c("sound\\quest_fin.wav", Nothing),
                c("sound\\sfx_weapon_eqp_pol.wav", Nothing),
            ],
        ),
        (
            "nfs-mw-07",
            vec![
                c(
                    "D3D11Installer\\D3D11Install.exe",
                    Rule(Category::RedistFile),
                ),
                c(
                    "D3D11Installer\\D3D11InstallHelper.dll",
                    Rule(Category::RedistFolder),
                ),
            ],
        ),
        (
            "aquaria-09",
            vec![
                c("gfx\\anemone-bg.png", Nothing),
                c("gfx\\froog-fin.png", Nothing),
                c("gfx\\turtle-fin.png", Nothing),
                c("gfx\\no.png", Nothing),
                c("gfx\\sky-bg.png", Nothing),
                c("gfx\\temple-bg.png", Nothing),
                c("gfx\\waterfall-bg.png", Nothing),
                c("gfx\\gui\\check-bg.png", Nothing),
                c("gfx\\gui\\scroll-da-down.png", Nothing),
                c("gfx\\gui\\scroll-da-up.png", Nothing),
                c("gfx\\gui\\slider-bg.png", Nothing),
            ],
        ),
        (
            "half-life-bshift-11",
            vec![
                c("bshift\\sound\\aslave\\slv_alert1.wav", Nothing),
                c("bshift\\sound\\aslave\\slv_die1.wav", Nothing),
                c("bshift\\sound\\aslave\\slv_word1.wav", Nothing),
                c("valve\\sound\\aslave\\slv_pain1.wav", Nothing),
            ],
        ),
        (
            "fall-of-avalon-13",
            vec![
                c(
                    "Fall of Avalon_Data\\StreamingAssets\\FmodBanks\\Dan.bank",
                    Nothing,
                ),
                c(
                    "Fall of Avalon_Data\\StreamingAssets\\FmodBanks\\FV_Ron_Innkeeper_AboutTavern.bank",
                    Nothing,
                ),
                c(
                    "Fall of Avalon_Data\\StreamingAssets\\FmodBanks\\HoSGeneric_Guard_Dan_Coat_Controller.bank",
                    Nothing,
                ),
            ],
        ),
        (
            "morrowind-tr-14-15",
            vec![
                c("Data Files\\icons\\tr\\tr_a_gauntletspoor.dds", Nothing),
                c("Data Files\\icons\\tr\\tr_a_hr_gnomes_uni.dds", Nothing),
                c("Data Files\\icons\\tr\\tr_a_ind_shield_01.dds", Nothing),
                c("Data Files\\Textures\\tr\\tr_wood_de_rm02.dds", Nothing),
                c("Data Files\\Textures\\tx\\tx_hr_market_canvas00.dds", Nothing),
                c("Data Files\\Textures\\tx\\tx_pt_broadbrush.dds", Nothing),
                c(
                    "Data Files\\Textures\\tx\\tx_skyrim_ind_bloodstone_01.dds",
                    Nothing,
                ),
            ],
        ),
        (
            "cod-mw-16",
            vec![
                c("captive_basement_tr.ff", Nothing),
                c("captive_basement_tr.fp", Nothing),
                c("captive_exterior_tr.ff", Nothing),
                c("cp_arms_dealer_00001_tr.ff", Nothing),
                c("cp_arms_dealer_00002_tr.ff", Nothing),
            ],
        ),
        (
            "ets2-17",
            vec![
                c("dlc_flags_bg.scs", Nothing),
                c("dlc_flags_de.scs", Nothing),
                c("dlc_flags_es.scs", Nothing),
                c("dlc_flags_fi.scs", Nothing),
                c("dlc_flags_fr.scs", Nothing),
                c("dlc_flags_hu.scs", Nothing),
                c("dlc_flags_it.scs", Nothing),
                c("dlc_flags_nl.scs", Nothing),
                c("dlc_flags_pl.scs", Nothing),
                c("dlc_flags_ru.scs", Nothing),
                c("dlc_flags_tr.scs", Nothing),
                c("dlc_dutch_style.scs", Nothing),
                c("dlc_greek_paintjobs.scs", Nothing),
            ],
        ),
        (
            "brg-18",
            vec![
                c(
                    "BrgGame\\CookedPCConsole\\AS_CH_MidBoss_No01_SF_LOC_JPN.upk",
                    Loc("ja"),
                ),
                c(
                    "BrgGame\\CookedPCConsole\\BrgOpeningMovie_LOC_JPN.upk",
                    Loc("ja"),
                ),
                c(
                    "BrgGame\\CookedPCConsole\\Cafe_BG_ImageTraining.upk",
                    Nothing,
                ),
                c("BrgGame\\CookedPCConsole\\Cafe_BG_Platform_G.upk", Nothing),
                c(
                    "BrgGame\\CookedPCConsole\\Cafe_BG_Platform_Joint.upk",
                    Nothing,
                ),
                c("BrgGame\\CookedPCConsole\\Cafe_BG_Toilet_KIS.upk", Nothing),
                c(
                    "BrgGame\\CookedPCConsole\\Cafe_BG_Toilet_KIS_LOC_JPN.upk",
                    Loc("ja"),
                ),
            ],
        ),
        (
            "amnesia-rebirth-19",
            vec![
                c(
                    "entities\\french_colonization\\furniture\\cabinet01.ent",
                    Nothing,
                ),
                c("entities\\french_colonization\\lamp\\lamp01.ent", Nothing),
                c("entities\\arabic_fort\\door\\door01.ent", Nothing),
                c("static_objects\\arabic_fort\\wall01.dae", Nothing),
                c("static_objects\\french_colonization\\fence01.dae", Nothing),
            ],
        ),
        (
            "red-faction-20",
            vec![
                c("build\\pc\\cache\\M01_CS_00.bik", Nothing),
                c("build\\pc\\cache\\M06_CS_05.bik", Nothing),
                c("build\\pc\\cache\\M13_CS_14_MO_WBarge.bik", Nothing),
                c("build\\pc\\cache\\Q01_CS_04.bik", Nothing),
                // This label has been flipped twice and is worth a note. It was
                // `Nothing` when written, correctly: no intro rules existed yet.
                // GT-EP12 changed it to `Intro` after a human looked at the file
                // - a legal screen is exactly what the intro feature removes.
                // GT-EP10 then changed it back, justifying it by its own new
                // policy that Bink is reserved for the archive inspector. That was
                // ground truth being edited to agree with code, which is the one
                // thing this corpus must never do. Bink 1 is an intro video again
                // (GT-204), so the human judgement stands.
                c("build\\pc\\cache\\legal_hd_no_esrb.bik", Rule(Category::Intro)),
                c("build\\pc\\cache\\RF4_MainMenuBG.bik", Nothing),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_AR.vpp_pc", LocAny),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_DE.vpp_pc", Loc("de")),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_ES.vpp_pc", Loc("es")),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_FR.vpp_pc", Loc("fr")),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_IT.vpp_pc", Loc("it")),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_PL.vpp_pc", Loc("pl")),
                c("build\\dlc04\\pc\\cache\\dlc04_voices_RU.vpp_pc", Loc("ru")),
            ],
        ),
        (
            "ark-22",
            vec![
                c(
                    "ShooterGame\\Content\\Genesis2\\Environment\\Eden\\Valley\\Vegetation\\Trees\\ItalianCypress\\italiancypress01.uasset",
                    Nothing,
                ),
                c(
                    "ShooterGame\\Content\\Extinction\\Environment\\Ruins\\City\\Vegetation\\Trees\\KoreanStewartia\\koreanstewartia01.uasset",
                    Nothing,
                ),
                c(
                    "ShooterGame\\Content\\ScorchedEarth\\Environment\\Shared\\Vegetation\\Foliage\\SpanishBayonet\\spanishbayonet01.uasset",
                    Nothing,
                ),
                c(
                    "ShooterGame\\Content\\Localization\\Game\\ja\\Game.archive",
                    Loc("ja"),
                ),
                c(
                    "ShooterGame\\Content\\Localization\\Game\\ko\\Game.archive",
                    Loc("ko"),
                ),
                c(
                    "ShooterGame\\Content\\Localization\\Game\\zh-TWA\\Game.archive",
                    LocAny,
                ),
                c(
                    "ShooterGame\\Content\\Genesis\\Sound\\Characters\\HLNA\\Glitches\\Portuguese\\glitch01.wem",
                    Loc("pt"),
                ),
                c(
                    "ShooterGame\\Content\\Genesis\\Sound\\Characters\\HLNA\\Glitches\\German\\glitch01.wem",
                    Loc("de"),
                ),
                c(
                    "ShooterGame\\Content\\Genesis\\Sound\\Characters\\HLNA\\Glitches\\Italian\\glitch01.wem",
                    Loc("it"),
                ),
                c(
                    "ShooterGame\\Content\\Genesis\\Sound\\Characters\\HLNA\\Glitches\\Japanese\\glitch01.wem",
                    Loc("ja"),
                ),
            ],
        ),
        (
            "thaumaturge-23",
            vec![
                c(
                    "TheThaumaturge\\Content\\Movies\\LoadingScreen_POL.mp4",
                    Nothing,
                ),
                c(
                    "TheThaumaturge\\Content\\Movies\\vp9\\LoadingScreen_POL.mp4",
                    Nothing,
                ),
            ],
        ),
        (
            "hawx2-25",
            vec![
                c("Data\\Movies\\M20_Russian_Standoff10.sub", Nothing),
                c("Data\\Movies\\M20_Russian_Standoff12.sub", Nothing),
                c("Data\\Movies\\M20_Russian_Standoff16.sub", Nothing),
                c("Data\\Movies\\M20_Russian_Standoff21.sub", Nothing),
            ],
        ),
        (
            "ace-combat-26",
            vec![
                c(
                    "dlc_26\\DLC02_MQ005_C020_SC010_CS_Opening_Scene.bk2",
                    Nothing,
                ),
                c("dlc_26\\ACE_pc_dlc_26_fre.pck", LocAny),
                c("dlc_26\\ACE_pc_dlc_26_ger.pck", LocAny),
                c("dlc_26\\ACE_pc_dlc_26_ita.pck", LocAny),
                c("dlc_26\\ACE_pc_dlc_26_rus.pck", LocAny),
            ],
        ),
        (
            "mafia2-27",
            vec![
                c("pc\\sds_de\\speech\\speech.sds", Loc("de")),
                c("pc\\sds_fr\\speech\\speech.sds", Loc("fr")),
                c("pc\\sds_jp\\speech\\speech.sds", Loc("ja")),
                c("pc\\sds_ru\\speech\\speech.sds", Loc("ru")),
                c("pc\\sds_cz\\speech\\speech.sds", Loc("cs")),
                c("pc\\sds_pl\\speech\\speech.sds", Loc("pl")),
                c("pc\\sds_it\\speech\\speech.sds", Loc("it")),
                c("pc\\sds_spa\\speech\\speech.sds", Loc("es")),
                c("pc\\sds_latam\\gui\\gui.sds", LocAny),
                c("pc\\sds_en\\speech\\speech.sds", Nothing),
                c("pc\\APEX_Clothing.dll", Nothing),
                c(
                    "pc\\dlcs\\cnt_betrayal_of_jimmy\\game_edit\\tables\\TextDatabase_DLC_Prequel_fr.dat",
                    Loc("fr"),
                ),
                c(
                    "pc\\dlcs\\cnt_betrayal_of_jimmy\\game_edit\\tables\\TextDatabase_DLC_Prequel_it.dat",
                    Loc("it"),
                ),
                c(
                    "pc\\dlcs\\cnt_betrayal_of_jimmy\\game_edit\\tables\\TextDatabase_DLC_Prequel_pl.dat",
                    Loc("pl"),
                ),
                c(
                    "pc\\dlcs\\cnt_betrayal_of_jimmy\\game_edit\\tables\\TextDatabase_DLC_Prequel_ru.dat",
                    Loc("ru"),
                ),
                c(
                    "pc\\dlcs\\cnt_betrayal_of_jimmy\\game_edit\\tables\\TextDatabase_DLC_Prequel_en.dat",
                    Nothing,
                ),
            ],
        ),
        (
            "wonderlands-28",
            vec![
                c(
                    "OakGame\\Content\\Movies\\indigo2\\indoCIN_PLC2W1_5.1mix_LOC.mp4",
                    Nothing,
                ),
                c(
                    "OakGame\\Content\\Movies\\indigo2\\indoCIN_PLC2W2_5.1mix_LOC.mp4",
                    Nothing,
                ),
                c(
                    "OakGame\\Content\\Movies\\indigo2\\indoCIN_PLC2W3_5.1mix_LOC.mp4",
                    Nothing,
                ),
            ],
        ),
        (
            "grid-29",
            vec![
                c(
                    "audio\\speech\\en\\13_drift\\collision_drift_jpn_01.raw",
                    Nothing,
                ),
                c(
                    "audio\\speech\\en\\13_drift\\collision_drift_jpn_02.raw",
                    Nothing,
                ),
                c(
                    "audio\\speech\\en\\13_drift\\collision_drift_jpn_17.raw",
                    Nothing,
                ),
                c(
                    "audio\\speech\\ge\\13_drift\\collision_drift_jpn_01.raw",
                    LocAny,
                ),
                c(
                    "audio\\speech\\fr\\13_drift\\collision_drift_jpn_01.raw",
                    Loc("fr"),
                ),
                c(
                    "audio\\speech\\it\\13_drift\\collision_drift_jpn_01.raw",
                    Loc("it"),
                ),
            ],
        ),
        (
            "da-origins-31",
            vec![
                c("data\\launcher\\bu1_hi.bmp", Nothing),
                c("data\\launcher\\bu2_hi.bmp", Nothing),
                c("data\\launcher\\bu7_hi.bmp", Nothing),
                c("data\\launcher\\close_hi.bmp", Nothing),
                c("data\\launcher\\min_hi.bmp", Nothing),
                c("data\\launcher\\mute_hi.bmp", Nothing),
                // origins_hu/pl/ru ARE per-language launcher bitmaps, but a
                // 3-language bare-code shape family sits below the
                // Pathfinder-calibrated threshold (see
                // MIN_SHAPE_FAMILY_SIZE_BARE_ONLY) — accepted conservative
                // miss, the report did not ask for these.
                c("data\\launcher\\origins_hu.bmp", Nothing),
                c("data\\launcher\\origins_pl.bmp", Nothing),
                c("data\\launcher\\origins_ru.bmp", Nothing),
            ],
        ),
        (
            "zombie-army-32-33",
            vec![
                c("Envs\\ItalianCity\\italiancity.pc", Nothing),
                c("Envs\\ItalianCity\\m_italiancity.pc", Nothing),
                c("Envs\\ItalianCity\\m_italiancity.pc_cs", Nothing),
                c("Envs\\ItalianCity\\m_italiancity.pc_en", Nothing),
                c("Envs\\ItalianCity\\m_italiancity.pc_entdata", Nothing),
                c(
                    "navmesh\\ItalianCity\\m_italiancity_actor.navmesh",
                    Nothing,
                ),
                c("sounds\\gmsndmeta.asr_cs", Loc("cs")),
                c("sounds\\gmsndmeta.asr_fr", Loc("fr")),
                c("sounds\\gmsndmeta.asr_it", Loc("it")),
                c("sounds\\gmsndmeta.asr_ko", Loc("ko")),
                c("sounds\\gmsndmeta.asr_pl", Loc("pl")),
                c("sounds\\gmsndmeta.asr_ru", Loc("ru")),
            ],
        ),
        (
            "redout-34",
            vec![c(
                "redout\\Content\\FMOD\\Desktop_51\\BKG_ItalianCoast.bank",
                Nothing,
            )],
        ),
        (
            "xcom-chimera-35-36",
            vec![
                c("XComGame\\CookedPCConsole\\wp_consp_ar_SF.upk", Nothing),
                c(
                    "XComGame\\CookedPCConsole\\HolographicKiosksA_Hi_1x1.upk",
                    Nothing,
                ),
                c("XComGame\\CookedPCConsole\\uefonts_jpn_SF.upk", LocAny),
                c("XComGame\\CookedPCConsole\\uefonts_kor_SF.upk", LocAny),
                c(
                    "XComGame\\CookedPCConsole\\FemaleVoice9_German_SF.upk",
                    Loc("de"),
                ),
                c(
                    "XComGame\\CookedPCConsole\\FemaleVoice9_Italian_SF.upk",
                    Loc("it"),
                ),
                c(
                    "XComGame\\CookedPCConsole\\FemaleVoice9_Spanish_SF.upk",
                    Loc("es"),
                ),
                c("XComGame\\Movies\\XCS_LegalScreen_DEU.bk2", Loc("de")),
                c("XComGame\\Movies\\XCS_LegalScreen_FRA.bk2", Loc("fr")),
                c("XComGame\\Movies\\XCS_LegalScreen_ITA.bk2", Loc("it")),
                c("XComGame\\Movies\\XCS_LegalScreen_JPN.bk2", Loc("ja")),
            ],
        ),
        (
            "sang-froid-38-39",
            vec![
                c("media\\flechesDirectionRavage_NO.png", Nothing),
                c("media\\Footsteps_Snow_Walk_PL_01.wav", Nothing),
                c("media\\Footsteps_Snow_Walk_PL_02.wav", Nothing),
                c("media\\Footsteps_Snow_Walk_PL_13.wav", Nothing),
                c("media\\PRETRE_D_12_1_1_FR.wav", Nothing),
                c("media\\PRETRE_D_12_1_2_FR.wav", Nothing),
                c("media\\playersStatsPMTitle_FR.png", Nothing),
            ],
        ),
        (
            "burnout-43",
            vec![
                c(
                    "LANGUAGE\\FONTS\\WESTERNB5BODY_CZCH_HUN_35.FONT",
                    Loc("cs"),
                ),
                c(
                    "LANGUAGE\\FONTS\\WESTERNB5HEADER_CZCH_HUN_70.FONT",
                    Loc("cs"),
                ),
                c("LANGUAGE\\FONTS\\B5BODY_THAI_35.FONT", Loc("th")),
                c("SOUND\\STREAMS\\RU\\AFB_100_SHOWTL_RU.SNS", Loc("ru")),
                c("SOUND\\STREAMS\\PL\\AFB_100_SHOWTL_PL.SNS", Loc("pl")),
                c("SOUND\\STREAMS\\DE\\AFB_100_SHOWTL_DE.SNS", Loc("de")),
                c("SOUND\\STREAMS\\ES\\AFB_100_SHOWTL_ES.SNS", Loc("es")),
                c("SOUND\\STREAMS\\IT\\AFB_100_SHOWTL_IT.SNS", Loc("it")),
                c("SOUND\\STREAMS\\FR\\AFB_100_SHOWTL_FR.SNS", Loc("fr")),
            ],
        ),
        (
            "starfield-44",
            vec![
                c("sl.common.dll", Nothing),
                c("sl.dlss.dll", Nothing),
                c("sl.dlss_g.dll", Nothing),
                c("sl.interposer.dll", Nothing),
                c("sl.nis.dll", Nothing),
                c("sl.reflex.dll", Nothing),
                c("Data\\SFBGS00D - Voices_de.ba2", Loc("de")),
                c("Data\\SFBGS00D - Voices_es.ba2", Loc("es")),
                c("Data\\SFBGS00D - Voices_fr.ba2", Loc("fr")),
                c("Data\\SFBGS00D - Voices_ja.ba2", Loc("ja")),
            ],
        ),
        (
            "overlord-45-46-52",
            vec![
                c("Resources\\CS Bedroom.prp", Nothing),
                c("Resources\\CS Citadel.prp", Nothing),
                c("Resources\\CS Minion.prp", Nothing),
                c("Resources\\CS Movies.prp", Nothing),
                c("Resources\\CS Wizard.prp", Nothing),
                c("Resources\\CS_Tower.prp", Nothing),
                c("Resources\\Wizard_SFX_CS.prp", Nothing),
                c("Resources\\PXTest\\GreekBuilding.obj", Nothing),
                c("Resources\\MinionVoiceData_FRENCH.pvp", Loc("fr")),
                c("Resources\\MinionVoiceData_GERMAN.pvp", Loc("de")),
                c("Resources\\MinionVoiceData_ITALIAN.pvp", Loc("it")),
                c("Resources\\MinionVoiceData_SPANISH.pvp", Loc("es")),
                c("Overlord_Loading_FRE.dds", Loc("fr")),
                c("Overlord_Loading_GER.dds", Loc("de")),
                c("Overlord_Loading_ITA.dds", Loc("it")),
                c("Overlord_Loading_SPA.dds", Loc("es")),
            ],
        ),
        (
            "endless-legend-47",
            vec![
                c(
                    "Public\\Tutorial\\SChinese\\Tutorial - Chapter 1.zip",
                    Rule(Category::DocsFolder),
                ),
                c(
                    "Public\\Tutorial\\French\\Tutorial - Chapter 1.zip",
                    Rule(Category::DocsFolder),
                ),
            ],
        ),
        (
            "rainbow-six-vegas-48-49",
            vec![
                c("KellerGame\\Content\\Movies\\05_Dantes\\DAN-PIP-00.bik", Nothing),
                c("KellerGame\\Content\\Movies\\05_Dantes\\DAN-PIP-02-A.bik", Nothing),
                c("KellerGame\\Content\\Movies\\05_Dantes\\DAN-SCR-00.bik", Nothing),
                c("KellerGame\\Content\\Movies\\MexicoIntro\\introFU.bik", Nothing),
                c("KellerGame\\Content\\Sounds\\int\\ar.SB0", Nothing),
                c("KellerGame\\Content\\Sounds\\int\\bg.SB0", Nothing),
                c("KellerGame\\Content\\Sounds\\int\\de.SB0", Nothing),
                c("KellerGame\\Content\\Sounds\\int\\ja.SB0", Nothing),
                c("KellerGame\\Content\\Sounds\\int\\ru.SB0", Nothing),
            ],
        ),
        (
            "gta4-50",
            vec![
                c("GTAIV\\common\\data\\fragments\\cj_ind_crate_4.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\cj_ind_light_1.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\cj_ja_auto.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\cj_ja_brick_1.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\cj_kor_huge_vase_2.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\ec_box_rus_1.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\ec_rus_crate1.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\gb_kor_lantern01.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\gb_pol_desk01.tune", Nothing),
                c("GTAIV\\common\\data\\fragments\\gb_pol_shelves01.tune", Nothing),
            ],
        ),
        (
            "state-of-decay-51",
            vec![
                c(
                    "StateOfDecay2\\Content\\Audio\\Banks\\wpn_pstl_9mm_czech_m8.uasset",
                    Nothing,
                ),
                c(
                    "StateOfDecay2\\Content\\WwiseAudio\\Windows\\wpn_pstl_9mm_czech_m8.bnk",
                    Nothing,
                ),
            ],
        ),
        (
            "scourge-53",
            vec![
                c(
                    "ScourgeGame\\CookedPCConsole\\ScourgeGame_LOC_JPN.upk",
                    Loc("ja"),
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L1_AlphaSighting1.upk",
                    Nothing,
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L1_AlphaSighting1_LOC_INT.upk",
                    Nothing,
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L1_Ambrosia.upk",
                    Nothing,
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L1_Ambrosia_LOC_INT.upk",
                    Nothing,
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L3_BlurFight.upk",
                    Nothing,
                ),
                c(
                    "ScourgeGame\\CookedPCConsole\\SP_CS_L3_BlurFight_LOC_INT.upk",
                    Nothing,
                ),
            ],
        ),
        (
            "journey-54",
            vec![
                c(
                    "Data\\Textures\\Bin\\Menu_Strings\\Menu_Strings_SpanishLA.dds.D3D11x64",
                    Nothing,
                ),
                c("Data\\Textures\\Bin\\NoSkyboxnone.dds", Nothing),
                c(
                    "Data\\Textures\\Bin\\Title_SonyLogo\\Title_SonyLogo_french.dds",
                    Nothing,
                ),
            ],
        ),
        (
            "coh2-55",
            vec![
                c("CoH2\\Movies\\defeat_german.lua", Nothing),
                c("CoH2\\Movies\\defeat_german.webm", Nothing),
                c("CoH2\\Movies\\flag_german.webm", Nothing),
                c("CoH2\\Movies\\flag_west_german.webm", Nothing),
                c("CoH2\\Movies\\victory_german.webm", Nothing),
                c("CoH2\\Movies\\victory_german_easy.webm", Nothing),
            ],
        ),
        (
            "conarium-56",
            vec![
                c(
                    "Engine\\Content\\Internationalization\\icudt53l\\bg.res",
                    Nothing,
                ),
                c(
                    "Engine\\Content\\Internationalization\\icudt53l\\bg_BG.res",
                    Nothing,
                ),
                c(
                    "Engine\\Content\\Internationalization\\icudt53l\\ar_SY.res",
                    Nothing,
                ),
                c(
                    "Engine\\Content\\Internationalization\\icudt53l\\brkirti\\de.res",
                    Nothing,
                ),
                c(
                    "Engine\\Content\\Internationalization\\icudt53l\\brkirti\\ja.res",
                    Nothing,
                ),
            ],
        ),
        (
            "shadowrun-57",
            vec![
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\DragonFallExtended\\data\\items\\russian grenade 3 (frag).item.bytes",
                    Nothing,
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\DragonFallExtended\\data\\items\\sr 3 steyr aug-csl.item.bytes",
                    Nothing,
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\dead_man_switch\\data\\loc\\de\\deadmanswitch.mo",
                    Loc("de"),
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\dead_man_switch\\data\\loc\\es\\deadmanswitch.mo",
                    Loc("es"),
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\dead_man_switch\\data\\loc\\fr\\deadmanswitch.mo",
                    Loc("fr"),
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\dead_man_switch\\data\\loc\\it\\deadmanswitch.mo",
                    Loc("it"),
                ),
                c(
                    "Dragonfall_Data\\StreamingAssets\\ContentPacks\\dead_man_switch\\data\\loc\\ru\\deadmanswitch.mo",
                    Loc("ru"),
                ),
            ],
        ),
        (
            "ut2004-58",
            vec![
                c("Textures\\DanFX.utx", Nothing),
                c("Textures\\DeRez.utx", Nothing),
                c("Textures\\ExitScreenNoLogo.utx", Nothing),
                c("Textures\\NaThCrossfire.utx", Nothing),
            ],
        ),
        (
            "pathfinder-wrath-59",
            vec![
                c("Bundles\\ee_body01_f_de.ee", Nothing),
                c("Bundles\\ee_body01_f_el.ee", Nothing),
                c("Bundles\\ee_body01_f_he.ee", Nothing),
                c("Bundles\\ee_body01_m_de.ee", Nothing),
                c("Bundles\\ee_body01_m_el.ee", Nothing),
                c("Bundles\\ee_body01_m_he.ee", Nothing),
                c("Bundles\\ee_brows01_f_de.ee", Nothing),
                c("Bundles\\ee_brows01_f_el.ee", Nothing),
                c("Bundles\\ee_brows01_f_he.ee", Nothing),
                c("Bundles\\ee_head01_m_de.ee", Nothing),
                c("Bundles\\ee_head01_m_el.ee", Nothing),
                c("Bundles\\ee_head01_m_he.ee", Nothing),
                c(
                    "Wrath_Data\\StreamingAssets\\Localization\\deDE.json",
                    Loc("de"),
                ),
            ],
        ),
        (
            "kotor2-60",
            vec![
                c("StreamVoice\\701\\KOR_INT\\kor701.wav", Nothing),
                c("StreamVoice\\602\\JEDI_RUM\\jedi602.wav", Nothing),
                c("StreamVoice\\AVO\\_DevoGre\\AVO_DevoGretM1.wav", Nothing),
                c("StreamVoice\\AVO\\_DevoGre\\AVO_DevoGretS1.wav", Nothing),
                c("StreamVoice\\AVO\\_DuroGre\\AVO_DuroGretS1.wav", Nothing),
                c("Movies\\DanMov01.blk", Nothing),
            ],
        ),
        (
            "wolfenstein-61",
            vec![
                c(
                    "SP\\base\\streampacks\\ai_voice_sk_vo_english.spk",
                    Nothing,
                ),
                c(
                    "SP\\base\\streampacks\\civilian_female_01_sl.spk",
                    Nothing,
                ),
                c("SP\\base\\streampacks\\civilian_male_01_sl.spk", Nothing),
                c("SP\\base\\streampacks\\civilian_male_02_sl.spk", Nothing),
                c(
                    "SP\\base\\streampacks\\destroyed_french_luxury_car_streaming.spk",
                    Nothing,
                ),
                c("SP\\base\\streampacks\\french_luxury_car.spk", Nothing),
                c("SP\\base\\streampacks\\german_luxury_car.spk", Nothing),
                c("SP\\base\\streampacks\\russian.spk", Nothing),
                c(
                    "SP\\base\\streampacks\\scripted_voice_sk_dig_vo_english.spk",
                    Nothing,
                ),
            ],
        ),
        (
            "amalgam-62",
            vec![
                c("amalgam\\resource\\cs.ttf", Nothing),
                c("amalgam\\resource\\closecaption_russian.txt", Loc("ru")),
                c("amalgam\\resource\\closecaption_schinese.txt", Loc("zh-hans")),
                c("amalgam\\resource\\closecaption_spanish.txt", Loc("es")),
                c("amalgam\\resource\\closecaption_tchinese.txt", Loc("zh-hant")),
                c("amalgam\\resource\\gameui_german.txt", Loc("de")),
                c("amalgam\\resource\\gameui_russian.txt", Loc("ru")),
                c("amalgam\\resource\\gameui_schinese.txt", Loc("zh-hans")),
                c("amalgam\\resource\\gameui_spanish.txt", Loc("es")),
                c("amalgam\\resource\\gameui_tchinese.txt", Loc("zh-hant")),
                c("ep2\\resource\\closecaption_czech.txt", Loc("cs")),
                c("ep2\\resource\\closecaption_danish.txt", Loc("da")),
                c("ep2\\resource\\closecaption_dutch.txt", Loc("nl")),
                c("ep2\\resource\\closecaption_finnish.txt", Loc("fi")),
            ],
        ),
        (
            "wreckfest-63",
            vec![
                c(
                    "data\\menu\\textures\\angle_meter_bg_400x48_raw.bmap",
                    Nothing,
                ),
                c("data\\menu\\textures\\gearbox_bg_52x52_raw.bmap", Nothing),
                c(
                    "data\\menu\\textures\\mainmenu_bg_1920x1200_raw.bmap",
                    Nothing,
                ),
                c(
                    "data\\menu\\textures\\pc_button_bg_26x24_raw.bmap",
                    Nothing,
                ),
                c(
                    "data\\menu\\textures\\serverbrowser_bg_1920x1200_raw.bmap",
                    Nothing,
                ),
                c(
                    "data\\menu\\textures\\settings_bg_1920x1200_raw.bmap",
                    Nothing,
                ),
                c(
                    "data\\menu\\textures\\startup_screen_3_de_1920x1080_raw.bmap",
                    LocAny,
                ),
                c(
                    "data\\menu\\textures\\startup_screen_3_es_1920x1080_raw.bmap",
                    LocAny,
                ),
                c(
                    "data\\menu\\textures\\startup_screen_3_fr_1920x1080_raw.bmap",
                    LocAny,
                ),
                c(
                    "data\\menu\\textures\\startup_screen_3_it_1920x1080_raw.bmap",
                    LocAny,
                ),
                c(
                    "data\\menu\\textures\\startup_screen_3_ru_1920x1080_raw.bmap",
                    LocAny,
                ),
                c("data\\localization\\db_russian.trns", Loc("ru")),
                c("data\\localization\\db_spanish.trns", Loc("es")),
            ],
        ),
        (
            "chaosbane-64",
            vec![
                c("Documents\\AchievementsInfo.ynm", Nothing),
                c("Documents\\CharactersCusto.ynm", Nothing),
                c("Documents\\FinishMoves.ynm", Nothing),
                c("Documents\\QuestsList.ynm", Nothing),
                c("Documents\\SaveReference.ynm", Nothing),
            ],
        ),
        (
            "styx-65",
            vec![
                c(
                    "Engine\\EditorResources\\WPF\\Localized\\UnrealEd.JPN.xaml",
                    Loc("ja"),
                ),
                c(
                    "Engine\\EditorResources\\WPF\\Localized\\UnrealEd.KOR.xaml",
                    Loc("ko"),
                ),
                c(
                    "Engine\\EditorResources\\WPF\\Localized\\UnrealEd.CHN.xaml",
                    Loc("zh-hans"),
                ),
                c(
                    "Engine\\EditorResources\\WPF\\Localized\\UnrealEd.INT.xaml",
                    Nothing,
                ),
            ],
        ),
        (
            "flatout3-66",
            vec![
                c("Misc\\Czech.DCL", Loc("cs")),
                c("Misc\\French.DCL", Loc("fr")),
                c("Misc\\German.DCL", Loc("de")),
                c("Misc\\Italian.DCL", Loc("it")),
                c("Misc\\Polish.DCL", Loc("pl")),
                c("Misc\\Russian.DCL", Loc("ru")),
                c("Misc\\Spanish.DCL", Loc("es")),
                c("Textures\\F_lt_01.DCT", Nothing),
                c("Textures\\F_lt_01b.DCT", Nothing),
                c("Textures\\Face2_sk.DCT", Nothing),
                c("Textures\\F_booRo.DCT", Nothing),
                c("Textures\\MountSV.DCT", Nothing),
                c("Textures\\MTSnw_De.DCT", Nothing),
                c("Textures\\Russian_3.DCT", Nothing),
                c("Textures\\Statue_JA.DCT", Nothing),
            ],
        ),
        (
            "vtm-redemption-67",
            vec![
                c("manual.pdf", Rule(Category::DocsFile)),
                c("Readme.rtf", Rule(Category::DocsFile)),
                c("Sounds.nob", Nothing),
            ],
        ),
        (
            "unknown-game-30",
            vec![
                c("CookedPC\\movies\\outro_de.usm", LocAny),
                c("CookedPC\\movies\\outro_es.usm", LocAny),
                c("CookedPC\\movies\\outro_fr.usm", LocAny),
                c("CookedPC\\movies\\outro_hu.usm", LocAny),
                c("CookedPC\\movies\\outro_it.usm", LocAny),
                c("CookedPC\\movies\\outro_pl.usm", LocAny),
                c("CookedPC\\movies\\outro_ru.usm", LocAny),
                c("CookedPC\\movies\\outro_tr.usm", LocAny),
                c("CookedPC\\sounds\\dlc_arena_crowd_cries_de.fsb", LocAny),
                c("CookedPC\\sounds\\dlc_arena_crowd_cries_fr.fsb", LocAny),
                c("CookedPC\\sounds\\dlc_arena_crowd_cries_pl.fsb", LocAny),
                c("CookedPC\\sounds\\dlc_arena_crowd_cries_ru.fsb", LocAny),
                c("CookedPC\\sounds\\l01_keep_cs.fsb", Nothing),
                c("CookedPC\\sounds\\l02_port_spa.fsb", Nothing),
                c("CookedPC\\sounds\\l03_camp_cs.fsb", Nothing),
            ],
        ),
        // GT-209: the intro rules distilled from the PCGamingWiki
        // "Skip intro videos" harvest (`docs/pcgw_skip_intro_dataset.json`).
        // Positives are real file names the wiki documents deleting; the
        // negatives below them are the names that merely *look* like the
        // positives - a frequent name is evidence that a name is common, not
        // that the video behind it is a logo, and an intro false positive
        // destroys a unique video nothing can re-download.
        (
            "gt-209-intro-harvest-positives",
            vec![
                // "logo" as a token, with a qualifier tail that carries a
                // digit - the shape a resolution or platform variant takes.
                c(
                    "ContentBaked\\pc\\BinkMovies\\2KG_logo_720P_PS4.bik",
                    Rule(Category::Intro),
                ),
                // "logo" leading: what follows it names whose logo it is,
                // and that is an open set of studio names.
                c("data\\extern\\videos\\logo_pb.bik", Rule(Category::Intro)),
                // "logo" trailing, no tail at all.
                c("Movies\\abstergo_logo.bik", Rule(Category::Intro)),
                // A studio ident, separator-delimited so it cannot reach
                // "accident", "identity" or "Trident".
                c("Movies\\ACC_Ubisoft_Ident_1080.bik", Rule(Category::Intro)),
                c("Movies\\Ident_Frontier_Arena.webm", Rule(Category::Intro)),
                // A legal screen behind a glued studio or platform prefix,
                // which neither prefix-anchored legal rule reached.
                c("media\\valve_xbox_legals.bik", Rule(Category::Intro)),
                c("Videos\\TQLegal.bik", Rule(Category::Intro)),
                // Engine name glued to "logo".
                c("Movies\\UE3Logo.bik", Rule(Category::Intro)),
                // Studio-prefixed splash screen, no tail.
                c("Content\\Movies\\AUROCH_SPLASHSCREEN.mp4", Rule(Category::Intro)),
                // Vendor logo glued into one word.
                c("Movies\\UbisoftLogo.bk2", Rule(Category::Intro)),
                // Legal/health screen behind a platform prefix.
                c("videos\\PC_WarningSaving.bk2", Rule(Category::Intro)),
                c("videos\\ps3_HealthWarning.bik", Rule(Category::Intro)),
                // Engine startup and splash screens.
                c(
                    "SwGame\\Content\\Movies\\Default_Startup.mp4",
                    Rule(Category::Intro),
                ),
                c(
                    "ArtificerOne\\Content\\Movies\\SplashScreen.mp4",
                    Rule(Category::Intro),
                ),
                // Generic developer/publisher ident.
                c("videos\\DeveloperIntro.usm", Rule(Category::Intro)),
                c("Data\\Video\\Publisher.bik", Rule(Category::Intro)),
                // Nothing but the publisher's name.
                c("data\\movies\\Sega.ogv", Rule(Category::Intro)),
                // Idle title-screen attract reel.
                c("videos\\attract.bk2", Rule(Category::Intro)),
            ],
        ),
        (
            "gt-209-intro-harvest-near-misses",
            vec![
                // "nologo" is the opposite of a logo: this is a demo outro
                // shipped *without* the logo reel.
                c("Movies\\demo_outro_nologo.bik", Nothing),
                // `intro.bik` is the single most frequent name in the harvest
                // and still not claimed: for as many games it is the opening
                // cinematic as it is the logo reel, and the corpus already
                // rules the story-cinematic reading (see `introFU.bik`).
                c("Movies\\intro.bik", Nothing),
                c("Movies\\cs_gameintro.ogv", Nothing),
                c("Movies\\OpeningCinematic.bik", Nothing),
                // A loading screen plays throughout the game, not at startup.
                c("Content\\Movies\\LoadingScreen.mp4", Nothing),
                // Frequent, but as easily the animated title card or a
                // fallback video as a logo.
                c("Movies\\title.avi", Nothing),
                c("Movies\\default.bik", Nothing),
                // "ident" only counts as a whole separator-delimited token.
                c("Movies\\Movie_Trident3.sfd", Nothing),
                c("Movies\\005_TheAccident.usm", Nothing),
                c("Movies\\Scenes_Alfred_Ak_Identity_Ch05.usm", Nothing),
                // The glued-prefix legal rule anchors on the *end* of the
                // name, so a legal district in a level name is out of reach.
                c("Movies\\LoadingDLC06LegalDistrict.bik", Nothing),
            ],
        ),
        // GT-209 follow-up, and the decision that settled it: a **screen the
        // game plays at you on the way in** is removed whatever language it
        // carries, and the keep-language list guards **content in your
        // language** instead. Every rule in the intro category names a screen
        // except the attract reel, which declares itself with
        // `localized_content` in `rules.json`.
        //
        // So all of these go, in every language, for every keep-list. The
        // alternative - what the app did for one round - was to remove the
        // eighteen legal screens the player cannot read and protect the one
        // that actually plays at startup.
        (
            "gt-209-language-suffixed-startup-screens-xcom",
            vec![
                c("XComGame\\Movies\\1080_LogoLegal_PCConsole.bik", Rule(Category::Intro)),
                c("XComGame\\Movies\\1080_LogoLegal_PCConsole_DEU.bik", Rule(Category::Intro)),
                c("XComGame\\Movies\\1080_LogoLegal_PCConsole_FRA.bik", Rule(Category::Intro)),
                c("XComGame\\Movies\\1080_LogoLegal_PCConsole_JPN.bik", Rule(Category::Intro)),
                // `INT` is the Unreal English master locale and English is
                // kept by default - and it still goes, because a legal screen
                // is a legal screen.
                c("XComGame\\Movies\\1080_LogoLegal_PCConsole_INT.bik", Rule(Category::Intro)),
            ],
        ),
        (
            "gt-209-language-suffixed-startup-screens-call-of-cthulhu",
            vec![
                c("Development\\pcvideo\\legal.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\legal_french.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\legal_german.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\legal_english.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\cocdcote_logo.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\cocdcote_logo_french.wmv", Rule(Category::Intro)),
                c("Development\\pcvideo\\cocdcote_logo_german.wmv", Rule(Category::Intro)),
            ],
        ),
        // The case the whole decision was about. Assassin's Creed keeps one
        // startup screen per language folder; the English one is the copy
        // that actually plays for a user who keeps English, and it is
        // removed along with the rest.
        (
            "gt-209-keep-language-folder-startup-screens",
            vec![
                c("videos\\en\\warning_disclaimer.bik", Rule(Category::Intro)),
                c("videos\\en\\PC_WarningSaving.bk2", Rule(Category::Intro)),
                c("videos\\de\\warning_disclaimer.bik", Rule(Category::Intro)),
                c("videos\\de\\PC_WarningSaving.bk2", Rule(Category::Intro)),
            ],
        ),
        // The other side of the line, and the only rule in the built-in pack
        // that sits on it: an attract reel is a five- to two-hundred-megabyte
        // gameplay video looping on the idle title screen, not something the
        // game plays at you. In a language the user keeps it is content and
        // survives; in one they do not it is removable like any other.
        (
            "gt-209-attract-reel-is-content-not-a-screen",
            vec![
                c("Movies\\attract.bik", Rule(Category::Intro)),
                c("movies\\english\\attract.bik", Nothing),
                c("movies\\german\\attract.bik", Rule(Category::Intro)),
            ],
        ),
    ]
}

fn rules_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("rules.json")
}

#[test]
fn report_golden_cases() {
    let engine = RuleEngine::load(&rules_path()).expect("repo rules.json should load");
    let detector = LangDetector::new();
    let mut failures: Vec<String> = Vec::new();

    for (game, cases) in games() {
        let files: Vec<FileEntry> = cases
            .iter()
            .map(|case| FileEntry::logical_only(case.path, 0, None))
            .collect();
        let loc: std::collections::HashMap<usize, LangFinding> =
            detector.analyze_game(&files).into_iter().collect();

        for (idx, case) in cases.iter().enumerate() {
            // Mirrors the app's combine_finding: a rule claim wins; a
            // localization finding applies only when no rule matched - and
            // the claim is dropped first if the keep-language list forbids
            // it, which is the guard both classification paths apply. The
            // detector here carries the default keep-list (`uk`, `en`), so
            // these cases describe what a user who keeps those two sees.
            // The corpus asks only "what would be flagged"; a keep-rule
            // veto is indistinguishable from a non-match for that question,
            // which is what `Verdict::flagged` exists for. `None` for the
            // app id: these cases are paths, not games, so no game-scoped
            // rule can apply to them.
            let rule = engine
                .classify(case.path, None)
                .flagged()
                .filter(|finding| {
                    !gametrimmer_core::worker::keep_language_vetoes_rule(
                        &detector, finding, case.path,
                    )
                });
            let lang = loc.get(&idx);

            let outcome: String = match (&rule, lang) {
                (Some(r), _) => format!("rule:{:?}", r.category),
                (None, Some(l)) => format!("loc:{} ({})", l.lang_tag, l.reason),
                (None, None) => "nothing".to_string(),
            };

            let ok = match &case.expect {
                Nothing => rule.is_none() && lang.is_none(),
                Loc(tag) => rule.is_none() && lang.map(|l| l.lang_tag == *tag).unwrap_or(false),
                LocAny => rule.is_none() && lang.is_some(),
                Rule(category) => rule
                    .as_ref()
                    .map(|r| r.category == *category)
                    .unwrap_or(false),
            };

            if !ok {
                let want = match &case.expect {
                    Nothing => "nothing".to_string(),
                    Loc(tag) => format!("loc:{tag}"),
                    LocAny => "loc:<any>".to_string(),
                    Rule(category) => format!("rule:{category:?}"),
                };
                failures.push(format!(
                    "[{game}] {}\n    want: {want}\n    got:  {outcome}",
                    case.path
                ));
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} report cases disagree:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
