[package]
name = "gametrimmer"
version.workspace = true
edition.workspace = true

[[bin]]
name = "gametrimmer"
path = "src/main.rs"

[dependencies]
eframe = "0.35.0"
gametrimmer-core = { path = "../core" }
rusqlite = { version = "0.40.1", features = ["bundled"] }

[dev-dependencies]
tempfile = "3.27.0"
