# scripts/all_language_data.py
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

# We load en.json and uk.json to build high fidelity translations
with open("locales/en.json", "r", encoding="utf-8") as f:
    en_data = json.load(f)
en = en_data["strings"]

with open("locales/uk.json", "r", encoding="utf-8") as f:
    uk = json.load(f)["strings"]

# Helper to load / update gld.DICTS
import generate_locales_data as gld

# Spanish (es)
es_dict = {
    "btn_scan_libraries": "Escanear bibliotecas",
    "btn_cancel": "Cancelar",
    "btn_export": "Exportar…",
    "btn_settings": "Configuración…",
    "btn_select_all": "Seleccionar todo",
    "btn_deselect_all": "Deseleccionar todo",
    "btn_delete_selected": "Eliminar seleccionados",
    "settings_section_general": "General",
    "settings_section_scanning": "Escaneo",
    "settings_section_selection": "Selección y eliminación",
    "settings_section_rules": "Reglas",
    "settings_section_data": "Datos y diagnósticos",
    "btn_done": "Listo",
    "btn_restore_defaults": "Restaurar valores predeterminados",
    "label_saved": "Guardado",
    "badge_immediately": "Inmediatamente",
    "badge_next_scan": "Desde el próximo escaneo",
    "badge_next_delete": "Desde la próxima eliminación",
    "default_profile_label": "Perfil inicial para nuevo escaneo",
    "default_profile_hint": "No cambia lo seleccionado actualmente — solo dónde comenzará el próximo escaneo.",
    "profile_cautious_hint": "Marca solo lo que el lanzador no restaurará por sí mismo: restos de juegos desinstalados, extras, documentación.",
    "profile_balanced_hint": "Lo mismo, más los archivos de idiomas fuera de su lista de conservación.",
    "profile_aggressive_hint": "Lo mismo, más redistribuibles y restos de instaladores.",
    "profile_custom_hint": "No marca nada por categoría — solo los archivos individuales con máxima certeza.",
    "confirm_behavior_label": "Confirmar antes de eliminar",
    "confirm_yes_label": "Sí",
    "confirm_no_label": "No",
    "confirm_behavior_hint": "Si está desactivado, la eliminación comienza inmediatamente al pulsar el botón.",
    "selection_independent_switches_hint": "Lo que se escanea, lo que se preselecciona y el método de eliminación son tres ajustes independientes.",
    "keep_languages_add_placeholder": "Añadir un idioma…",
    "categories_table_header_category": "Categoría",
    "categories_table_header_risk": "Riesgo",
    "categories_table_header_profile_behavior": "Perfil predeterminado",
    "profile_behavior_auto": "Preseleccionado",
    "profile_behavior_manual": "Nunca automático",
    "disabled_last_keep_language": "Al menos un idioma debe permanecer en la lista de conservación.",
    "disabled_last_category": "Al menos una categoría debe permanecer activada.",
    "disabled_last_library": "Al menos una biblioteca debe permanecer incluida en el escaneo.",
    "keep_english_warning": "Quitar el inglés no elimina nada directamente. Propondrá archivos de localización en inglés en el próximo escaneo.",
    "keep_english_absent": "El inglés no está en la lista: el escaneo propondrá archivos de idioma inglés.",
    "btn_keep_english_again": "Volver a conservar el inglés",
    "rules_pack_category_label": "Reglas de categorías (rules.json)",
    "rules_pack_lang_label": "Paquete de idiomas (l10n_rules.json)",
    "rules_valid_label": "Válido",
    "rules_invalid_label": "No válido",
    "db_path_label": "Archivo de base de datos:",
    "btn_copy": "Copiar",
    "btn_open_folder": "Abrir carpeta",
    "danger_zone_label": "ZONA DE PELIGRO",
    "disabled_busy": "Una operación en segundo plano está en curso",
    "disabled_no_findings": "Escanee primero sus bibliotecas",
    "disabled_no_selection": "No hay nada seleccionado",
    "disabled_export_running": "Ya se está ejecutando una exportación",
    "disabled_disclaimer": "Lea y acepte primero el descargo de responsabilidad en la pantalla de inicio",
    "disabled_database": "No se pudo abrir la base de datos",
    "profile_label": "Perfil:",
    "profile_cautious": "Prudente",
    "profile_balanced": "Equilibrado",
    "profile_aggressive": "Agresivo",
    "profile_custom": "Personalizado",
    "profile_hint": "Qué archivos vienen preseleccionados. Cambiar de perfil actualiza las marcas en el árbol.",
    "plan_filter_label": "Mostrar:",
    "plan_filter_all": "todas las categorías",
    "plan_group_label": "Agrupar por:",
    "group_axis_disk": "disco",
    "group_axis_launcher": "lanzador",
    "group_axis_library": "biblioteca",
    "group_axis_category": "categoría",
    "group_axis_flat": "ninguno",
    "group_unattributed": "Sin atribuir",
    "btn_remove_category": "Limpiar toda la categoría",
    "search_hint": "Buscar por nombre…",
    "btn_clear_search": "Borrar búsqueda",
    "search_no_matches": "Ningún resultado coincide con la búsqueda o el filtro actual.",
    "elevation_heading": "¿Acelerar el escaneo?",
    "elevation_body": "Al menos una biblioteca está en un disco duro (HDD). GameTrimmer puede leer la tabla NTFS ($MFT) directamente.",
    "elevation_when_asked": "Rechazar solo cuesta tiempo: el escaneo recorrerá las carpetas y encontrará los mismos archivos.",
    "btn_continue_without_elevation": "Continuar sin aceleración",
    "btn_relaunch_elevated": "Reiniciar como administrador",
    "elevation_never_ask": "No volver a preguntar",
    "confirm_delete_heading": "Confirmar eliminación",
    "confirm_label_permanent": "Eliminar permanentemente",
    "confirm_label_recycle": "Mover a la papelera de reciclaje",
    "remember_delete_method": "Recordar mi elección",
    "remove_summary_heading": "Resultado de la eliminación",
    "btn_close": "Cerrar",
    "confirm_clear_heading": "¿Vaciar la base de datos?",
    "confirm_clear_body": "Todos los resultados de escaneo y el registro de operaciones se eliminarán permanentemente.",
    "btn_confirm_clear": "Vaciar base de datos",
    "settings_heading": "Configuración",
    "delete_method_label": "Método de eliminación:",
    "delete_method_permanent_label": "Eliminación permanente (más rápida)",
    "delete_method_permanent_hint": "Los archivos se eliminan permanentemente sin pasar por la papelera.",
    "delete_method_recycle_label": "Papelera de reciclaje (más segura)",
    "delete_method_recycle_hint": "Los archivos se mueven a la Papelera de reciclaje de Windows.",
    "app_language_label": "Idioma de la aplicación:",
    "lang_name_system": "Según el idioma de Windows",
    "lang_name_en": "English",
    "lang_name_uk": "Українська",
    "theme_label": "Tema:",
    "theme_system_label": "Según el tema de Windows",
    "theme_light_label": "Claro",
    "theme_dark_label": "Oscuro",
    "logging_label": "Registro de depuración (gametrimmer.log):",
    "logging_enabled_label": "Activado",
    "logging_disabled_label": "Desactivado",
    "logging_hint": "Registra los eventos de la aplicación en el archivo gametrimmer.log junto al ejecutable.",
    "btn_open_log_file": "Abrir archivo de registro",
    "btn_open_log_folder": "Abrir carpeta de registro",
    "disclaimer_heading": "Antes de comenzar",
    "disclaimer_body": "GameTrimmer busca y elimina archivos innecesarios para jugar. Revise siempre los elementos antes de eliminar.",
    "disclaimer_accept_label": "Entiendo y acepto las condiciones",
    "btn_start_scan": "Iniciar escaneo",
    "status_idle": "Listo",
    "status_scanning": "Escaneando…",
    "status_deleting": "Eliminando…",
    "status_cancelling": "Cancelando operación…",
    "status_exporting": "Exportando…",
    "empty_libraries_title": "No se encontraron bibliotecas de juegos",
    "empty_libraries_body": "Los lanzadores de juegos no se detectaron automáticamente. Añada carpetas en la configuración de escaneo.",
    "empty_scan_title": "No se ha realizado ningún escaneo",
    "empty_scan_body": "Haga clic en «Escanear bibliotecas» para encontrar archivos innecesarios y liberar espacio.",
    "clean_scan_title": "¡Todo limpio!",
    "clean_scan_body": "No se encontraron archivos superfluos en sus bibliotecas de juegos.",
    "credits_heading": "Agradecimientos",
    "credits_anthropic": "Al equipo de Claude de Anthropic por su ayuda en el desarrollo.",
    "credits_karpathy": "A Andrej Karpathy por la inspiración en la creación de herramientas.",
    "credits_tikione": "Al autor de TikiOne Steam Cleaner por la idea y los primeros filtros.",
    "scanning_in_progress": "Escaneo en curso...",
    "no_findings_hint": "Sin resultados. Haga clic en «Escanear bibliotecas».",
    "col_language": "Idioma",
    "col_files": "Archivos",
    "col_size": "Tamaño",
    "col_name": "Nombre",
    "col_sort_hint": "Haga clic para ordenar por esta columna.",
    "review_mark_hint": "Revise este archivo antes de eliminarlo.",
    "hover_stub_note": "Se sustituye por un micro-stub para un inicio inmediato sin fallos.",
    "ctx_open": "Abrir",
    "ctx_reveal_in_explorer": "Mostrar en el Explorador",
    "ctx_open_with": "Abrir con…",
    "ctx_copy_path": "Copiar ruta",
    "ctx_never_touch": "No tocar nunca este archivo en este juego",
    "btn_find_standalone": "Buscar juegos fuera de lanzadores",
    "find_standalone_hint": "Lee la lista de desinstalación de Windows para programas no gestionados.",
    "standalone_candidates_header": "Instalados fuera de lanzadores — añada los que sean juegos:",
    "no_standalone_candidates": "No se encontró nada fuera de sus lanzadores.",
    "add_library_dialog_title": "Seleccione una carpeta de biblioteca",
    "export_dialog_title": "Exportar resultados del análisis",
    "text_file_filter_label": "Archivo de texto",
    "rules_export_dialog_title": "Seleccione una carpeta para exportar reglas",
    "rules_import_dialog_title": "Seleccione archivos de reglas para importar",
    "rules_import_filter_label": "Reglas de GameTrimmer (JSON)",
    "no_db_path": "Sin ruta de base de datos.",
    "db_path_error": "Error al determinar la ruta de la base de datos.",
    "detecting_libraries": "Detectando bibliotecas de juegos...",
    "preparing_database": "Preparando la base de datos...",
    "loading_previous_scan": "Cargando resultados anteriores...",
    "deleting_selected_files": "Eliminando archivos seleccionados...",
    "compacting_database": "Compactando la base de datos...",
    "clearing_database": "Vaciando la base de datos...",
    "scan_cancelled": "Escaneo cancelado.",
    "deletion_completed": "Eliminación completada.",
    "database_compacted": "Base de datos compactada.",
    "database_cleared": "Base de datos vaciada.",
    "settings_not_saved_no_path": "Configuración no guardada: no hay ruta a gametrimmer.ini.",
    "verb_analyze": "Analizando",
    "verb_delete": "Eliminando",
    "verb_compact": "Compactando base",
    "verb_clear": "Vaciando base",
    "verb_bundle": "Recopilando diagnóstico",
    "category_redist": "Paquetes redistribuibles",
    "category_intro": "Vídeos de introducción y logotipos",
    "category_docs": "Manuales y documentación",
    "category_bonus": "Contenido adicional",
    "category_loc": "Archivos de idiomas no utilizados",
    "category_other": "Otros archivos innecesarios",
    "category_orphan": "Restos de juegos desinstalados",
    "orphan_branch_label": "Restos huérfanos",
    "unit_gb": "GB",
    "unit_mb": "MB",
    "unit_kb": "KB",
    "unit_b": "B",
    "csv_yes": "sí",
    "csv_no": "no",
    "already_running_title": "GameTrimmer ya se está ejecutando"
}

gld.DICTS["es"] = es_dict
gld.DICTS["es-419"] = es_dict

print("Registered Spanish dictionaries.")
