"""Turn the harvested PCGamingWiki dataset into an analysis document.

Every name, count and example in the generated document is read out of
``docs/pcgw_skip_intro_dataset.json``. Nothing is written by hand - an earlier
analysis pass illustrated its categories with plausible-looking file names
(``unity_logo.mp4``, ``attract_mode.bik``) that appear nowhere in the data, and
a rule written from one of those would match nothing while looking correct.
Examples here are the highest-count real members of each group.

Run from the repository root, after the harvester:

    python scripts/analyze_pcgw_intros.py
"""

import json
import re
import sys
from collections import Counter

DATASET_PATH = "docs/pcgw_skip_intro_dataset.json"
ANALYSIS_PATH = "docs/pcgw_intro_analysis.md"

# How a file name is grouped. Ordered: the first group whose pattern matches
# the name wins, so a `nvidia_legal.bik` counts as a vendor bumper rather than
# a legal screen. Word-ish boundaries, because "ea" must not match "release"
# and "ue4" must not match "sue4".
GROUPS = [
    (
        "vendor",
        "Hardware and middleware vendors",
        r"nvidia|geforce|nvlogo|twimtbp|amd|radeon|ryzen|intel|bink|radvideo|rad_?game|"
        r"havok|physx|apex|unreal|\bue[345]\b|udk|unity|cryengine|crytek|dolby|\bdts\b|"
        r"wwise|fmod|scaleform|speedtree|autodesk|umbra|enlighten|denuvo|easyanticheat",
    ),
    (
        "publisher",
        "Publisher and developer idents",
        r"bethesda|zenimax|ubisoft|ubi_?|anvil|\bea\b|easig|electronic_?arts|origin|"
        r"activision|atvi|blizzard|capcom|konami|\bsega\b|bandai|namco|warner|\bwb\b|"
        r"rockstar|sony|playstation|xbox|microsoft|cdpr|cdprojekt|arkane|bioware|\bbw\b|"
        r"dice|gearbox|remedy|techland|paradox|eidos|square|focus|deep_?silver|\bthq\b|"
        r"\b2k\b|take2|milestone|codemasters|kalypso|atlus|koei|tecmo|fromsoftware|"
        r"larian|obsidian|valve|devolver|annapurna|bungie|epicgames|nixxes|avalanche|"
        r"saber|frontier|11bit|cdproject|gsc|sierra|lucasarts|interplay|ign|graymatr|lec",
    ),
    (
        "legal",
        "Legal, rating and warning screens",
        r"legal|esrb|pegi|cero|\busk\b|rating|disclaimer|warning|epilepsy|health|safety|"
        r"autosave|copyright|attention|notice|caution|eula|agerating",
    ),
    (
        "generic",
        "Generic intro, logo and startup names",
        r"intro|logos?|splash|startup|start_?up|boot|title|opening|attract|presents|"
        r"movie|video|loading|launch|prelude|teaser|bumper|stinger|ident|credits",
    ),
]


def group_of(name):
    stem = name.rsplit(".", 1)[0].lower()
    for key, _label, pattern in GROUPS:
        if re.search(pattern, stem):
            return key
    return "other"


def table(rows, headers):
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return lines


def main():
    with open(DATASET_PATH, encoding="utf-8") as handle:
        records = json.load(handle)

    files = Counter()
    args = Counter()
    methods = Counter()
    for record in records:
        files.update(record["video_files"])
        args.update(record["launch_arguments"])
        methods.update(record["methods"])

    with_files = sum(1 for r in records if r["video_files"])
    with_args = sum(1 for r in records if r["launch_arguments"])
    with_neither = sum(1 for r in records if not r["video_files"] and not r["launch_arguments"])

    grouped = {key: Counter() for key, _label, _pattern in GROUPS}
    grouped["other"] = Counter()
    for name, count in files.items():
        grouped[group_of(name)][name] = count

    lines = [
        "# PCGamingWiki intro-skip dataset: analysis",
        "",
        "Generated by `scripts/analyze_pcgw_intros.py` from",
        f"`{DATASET_PATH}`, which `scripts/harvest_pcgw_intros_full.py` collects.",
        "Every file name, argument and count below is read out of that dataset - none",
        "of the examples are written by hand.",
        "",
        "## What was collected",
        "",
        "The wiki's `Skip intro videos` section (and its wordings - `Skip splash",
        "screen`, `Disable intro videos`) is the only first-hand evidence of what a",
        "game's intro is made of. Discovery uses",
        "`action=query&list=search`, paged through the API's own `continue` token;",
        "content uses `action=query&prop=revisions&rvslots=main`, **50 titles per",
        "request** - which is what keeps the run under the wiki's rate limit.",
        "",
    ]

    lines += table(
        [
            ("Pages with an intro-skip section", len(records)),
            ("Pages naming at least one video file", with_files),
            ("Pages naming at least one launch argument", with_args),
            ("Pages naming neither", with_neither),
            ("Distinct video file names", len(files)),
            ("Distinct launch arguments", len(args)),
        ],
        ("Metric", "Count"),
    )

    lines += ["", "## Fix methods (a page may document several)", ""]
    lines += table(methods.most_common(), ("Method", "Pages"))

    repeated_files = [(f"`{name}`", count) for name, count in files.most_common() if count >= 3]
    lines += [
        "",
        f"## Video files named on 3 or more pages ({len(repeated_files)} names)",
        "",
        "These are the cross-game intro files - the ones a generic rule can be built",
        "from, because more than one game ships a file by that name.",
        "",
    ]
    lines += table(repeated_files, ("File", "Pages"))

    repeated_args = [(f"`{arg}`", count) for arg, count in args.most_common() if count >= 3]
    lines += [
        "",
        f"## Launch arguments used on 3 or more pages ({len(repeated_args)} arguments)",
        "",
        "These belong to a different subsystem than the file rules: nothing is deleted,",
        "the game is asked to skip its own intro (GT-155, Steam launch options).",
        "",
    ]
    lines += table(repeated_args, ("Argument", "Pages"))

    lines += ["", "## What the names look like", "", "Shape of the collected file names:", ""]
    lines += table(
        [
            (label, len(grouped[key]), sum(grouped[key].values()))
            for key, label, _pattern in GROUPS
        ]
        + [("Everything else", len(grouped["other"]), sum(grouped["other"].values()))],
        ("Group", "Distinct names", "Total pages"),
    )

    for key, label, _pattern in GROUPS + [("other", "Everything else", "")]:
        top = grouped[key].most_common(12)
        if not top:
            continue
        lines += [
            "",
            f"### {label} - {len(grouped[key])} names",
            "",
            "Most frequent members: " + ", ".join(f"`{name}` ({count})" for name, count in top),
        ]

    unusable = [
        r for r in records if not r["video_files"] and not r["launch_arguments"]
    ]
    unusable.sort(key=lambda r: r["title"])
    lines += [
        "",
        f"## Pages a file rule cannot be built from ({len(unusable)})",
        "",
        "The fix here is a config edit, a mod, or prose without a file name. Listed",
        "first 30 alphabetically, with the methods detected on the page.",
        "",
    ]
    lines += table(
        [(r["title"], ", ".join(r["methods"])) for r in unusable[:30]],
        ("Title", "Methods"),
    )

    with open(ANALYSIS_PATH, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")
    print(f"wrote {ANALYSIS_PATH}: {len(records)} records, {len(files)} distinct file names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
