@echo off
echo ========================================================
echo  GameTrimmer: Queuing Steam Game Installations
echo ========================================================

echo Installing Apex Legends (Source (Modified) - 65 GB)...
start "" "steam://install/1172470"
timeout /t 2 /nobreak >nul
echo Installing Destiny 2 (Tiger Engine - 105 GB)...
start "" "steam://install/1085660"
timeout /t 2 /nobreak >nul
echo Installing Overwatch 2 (Tank Engine (Blizzard) - 50 GB)...
start "" "steam://install/2357570"
timeout /t 2 /nobreak >nul
echo Installing Marvel Rivals (Unreal Engine 5 - 40 GB)...
start "" "steam://install/2767030"
timeout /t 2 /nobreak >nul
echo Installing PUBG: BATTLEGROUNDS (Unreal Engine 4 - 35 GB)...
start "" "steam://install/578080"
timeout /t 2 /nobreak >nul
echo Installing THE FINALS (Unreal Engine 5 - 20 GB)...
start "" "steam://install/2073850"
timeout /t 2 /nobreak >nul
echo Installing Halo Infinite (Slipspace Engine - 35 GB)...
start "" "steam://install/1240440"
timeout /t 2 /nobreak >nul
echo Installing The First Descendant (Unreal Engine 5 - 45 GB)...
start "" "steam://install/2074920"
timeout /t 2 /nobreak >nul
echo Installing Delta Force (Unreal Engine 5 - 50 GB)...
start "" "steam://install/2507950"
timeout /t 2 /nobreak >nul
echo Installing Shatterline (CryEngine / Lumberyard - 25 GB)...
start "" "steam://install/2087030"
timeout /t 2 /nobreak >nul
echo Installing Splitgate (Unreal Engine 4 - 20 GB)...
start "" "steam://install/677620"
timeout /t 2 /nobreak >nul
echo Installing Vampire: The Masquerade - Bloodhunt (Unreal Engine 4 - 30 GB)...
start "" "steam://install/760160"
timeout /t 2 /nobreak >nul
echo Installing Counter-Strike 2 (Source 2 - 35 GB)...
start "" "steam://install/730"
timeout /t 2 /nobreak >nul
echo Installing Dota 2 (Source 2 - 45 GB)...
start "" "steam://install/570"
timeout /t 2 /nobreak >nul
echo Installing Team Fortress 2 (Source - 22 GB)...
start "" "steam://install/440"
timeout /t 2 /nobreak >nul
echo Installing Path of Exile (Proprietary - 40 GB)...
start "" "steam://install/238960"
timeout /t 2 /nobreak >nul
echo Installing Warframe (Evolution Engine - 40 GB)...
start "" "steam://install/230410"
timeout /t 2 /nobreak >nul
echo Installing Lost Ark (Unreal Engine 3 - 75 GB)...
start "" "steam://install/1599340"
timeout /t 2 /nobreak >nul
echo Installing THRONE AND LIBERTY (Unreal Engine 4 - 60 GB)...
start "" "steam://install/2429640"
timeout /t 2 /nobreak >nul
echo Installing Once Human (NeoX Engine - 55 GB)...
start "" "steam://install/2139460"
timeout /t 2 /nobreak >nul
echo Installing STAR WARS: The Old Republic (HeroEngine - 50 GB)...
start "" "steam://install/1286830"
timeout /t 2 /nobreak >nul
echo Installing Guild Wars 2 (Proprietary - 70 GB)...
start "" "steam://install/1985790"
timeout /t 2 /nobreak >nul
echo Installing EVE Online (Carbon Engine - 30 GB)...
start "" "steam://install/8500"
timeout /t 2 /nobreak >nul
echo Installing Albion Online (Unity - 15 GB)...
start "" "steam://install/761890"
timeout /t 2 /nobreak >nul
echo Installing Tower of Fantasy (Unreal Engine 4 - 35 GB)...
start "" "steam://install/2064650"
timeout /t 2 /nobreak >nul
echo Installing Star Trek Online (Cryptic Engine - 25 GB)...
start "" "steam://install/9900"
timeout /t 2 /nobreak >nul
echo Installing Neverwinter (Cryptic Engine - 25 GB)...
start "" "steam://install/109600"
timeout /t 2 /nobreak >nul
echo Installing DC Universe Online (Unreal Engine 3 - 35 GB)...
start "" "steam://install/24200"
timeout /t 2 /nobreak >nul
echo Installing War Thunder (Dagor Engine - 55 GB)...
start "" "steam://install/236390"
timeout /t 2 /nobreak >nul
echo Installing World of Tanks (Core Engine - 60 GB)...
start "" "steam://install/1407200"
timeout /t 2 /nobreak >nul
echo Installing World of Warships (BigWorld Engine - 65 GB)...
start "" "steam://install/552990"
timeout /t 2 /nobreak >nul
echo Installing World of Warplanes (BigWorld Engine - 35 GB)...
start "" "steam://install/790710"
timeout /t 2 /nobreak >nul
echo Installing Enlisted (Dagor Engine - 40 GB)...
start "" "steam://install/2055400"
timeout /t 2 /nobreak >nul
echo Installing Crossout (Targem Engine - 15 GB)...
start "" "steam://install/386180"
timeout /t 2 /nobreak >nul
echo Installing Star Conflict (Targem Engine - 15 GB)...
start "" "steam://install/212070"
timeout /t 2 /nobreak >nul
echo Installing Paladins (Unreal Engine 3 - 28 GB)...
start "" "steam://install/444090"
timeout /t 2 /nobreak >nul
echo Installing SMITE (Unreal Engine 3 - 30 GB)...
start "" "steam://install/386360"
timeout /t 2 /nobreak >nul
echo Installing Predecessor (Unreal Engine 5 - 25 GB)...
start "" "steam://install/961200"
timeout /t 2 /nobreak >nul
echo Installing NARAKA: BLADEPOINT (Unity - 35 GB)...
start "" "steam://install/1203220"
timeout /t 2 /nobreak >nul
echo Installing Century: Age of Ashes (Unreal Engine 4 - 15 GB)...
start "" "steam://install/918450"
timeout /t 2 /nobreak >nul
echo Installing Unturned (Unity - 5 GB)...
start "" "steam://install/304930"
timeout /t 2 /nobreak >nul
echo Installing Brawlhalla (Proprietary - 2 GB)...
start "" "steam://install/291550"
timeout /t 2 /nobreak >nul
echo Installing The Sims 4 (SmartSim - 20 GB)...
start "" "steam://install/1222670"
timeout /t 2 /nobreak >nul
echo Installing Crusader Kings II (Clausewitz - 5 GB)...
start "" "steam://install/203770"
timeout /t 2 /nobreak >nul
echo Installing Disney Speedstorm (Unreal Engine 4 - 18 GB)...
start "" "steam://install/1537830"
timeout /t 2 /nobreak >nul
echo Installing KartRider: Drift (Unreal Engine 4 - 25 GB)...
start "" "steam://install/1184140"
timeout /t 2 /nobreak >nul
echo Installing Supermarket Together (Unity - 4 GB)...
start "" "steam://install/2708450"
timeout /t 2 /nobreak >nul
echo Installing Goose Goose Duck (Unity - 3 GB)...
start "" "steam://install/1568590"
timeout /t 2 /nobreak >nul
echo Installing Black Myth: Wukong Benchmark Tool (Unreal Engine 5 - 8 GB)...
start "" "steam://install/3132990"
timeout /t 2 /nobreak >nul
echo Installing 3DMark Demo (Proprietary - 6 GB)...
start "" "steam://install/231350"
timeout /t 2 /nobreak >nul
echo Installing Blender (Open Source 3D - 1.5 GB)...
start "" "steam://install/365670"
timeout /t 2 /nobreak >nul
echo Installing FINAL FANTASY XVI DEMO (Proprietary - 18 GB)...
start "" "steam://install/2738000"
timeout /t 2 /nobreak >nul
echo Installing Metaphor: ReFantazio Prologue Demo (GFD Engine (Atlus) - 30 GB)...
start "" "steam://install/2679460"
timeout /t 2 /nobreak >nul
echo Installing Street Fighter 6 Demo (RE Engine - 16 GB)...
start "" "steam://install/2154900"
timeout /t 2 /nobreak >nul
echo Installing Resident Evil 4 Chainsaw Demo (RE Engine - 11 GB)...
start "" "steam://install/2243880"
timeout /t 2 /nobreak >nul
echo Installing Detroit: Become Human Demo (Quantic Dream Engine - 10 GB)...
start "" "steam://install/1105510"
timeout /t 2 /nobreak >nul
echo Installing RoboCop: Rogue City Demo (Unreal Engine 5 - 25 GB)...
start "" "steam://install/2515080"
timeout /t 2 /nobreak >nul
echo Installing Lies of P Demo (Unreal Engine 4 - 20 GB)...
start "" "steam://install/2384010"
timeout /t 2 /nobreak >nul
echo Installing Ghostrunner 2 Demo (Unreal Engine 5 - 12 GB)...
start "" "steam://install/2518420"
timeout /t 2 /nobreak >nul
echo Installing The Talos Principle 2 Demo (Unreal Engine 5 - 15 GB)...
start "" "steam://install/2577610"
timeout /t 2 /nobreak >nul
echo Installing Pacific Drive Demo (Unreal Engine 4 - 14 GB)...
start "" "steam://install/2769490"
timeout /t 2 /nobreak >nul
echo Installing Visions of Mana Demo (Unreal Engine 4 - 15 GB)...
start "" "steam://install/2898490"
timeout /t 2 /nobreak >nul
echo Installing Kunitsu-Gami: Path of the Goddess Demo (RE Engine - 8 GB)...
start "" "steam://install/2908860"
timeout /t 2 /nobreak >nul
echo Installing OUTRIDERS Demo (Unreal Engine 4 - 22 GB)...
start "" "steam://install/1433600"
timeout /t 2 /nobreak >nul
echo Installing DRAGON QUEST XI S Demo (Unreal Engine 4 - 15 GB)...
start "" "steam://install/1354890"
timeout /t 2 /nobreak >nul
echo Installing Life is Strange (Episode 1) (Unreal Engine 3 - 3 GB)...
start "" "steam://install/319630"
timeout /t 2 /nobreak >nul

echo [DONE] All installation requests sent to Steam Client.