# scripts/translate_all_steam_languages.py
import json
import os
import sys

sys.stdout.reconfigure(encoding='utf-8')

# Read en.json as source
with open("locales/en.json", "r", encoding="utf-8") as f:
    en_data = json.load(f)
en_strings = en_data["strings"]

# Read uk.json
with open("locales/uk.json", "r", encoding="utf-8") as f:
    uk_data = json.load(f)
uk_strings = uk_data["strings"]

# Load generated ru, de, pl from gld
import generate_locales_data as gld
import build_all_dictionaries as bad

# Base vocabulary for French (fr)
fr_dict = {
    "btn_scan_libraries": "Analyser les bibliothèques",
    "btn_cancel": "Annuler",
    "btn_export": "Exporter…",
    "btn_settings": "Paramètres…",
    "btn_select_all": "Tout sélectionner",
    "btn_deselect_all": "Tout désélectionner",
    "btn_delete_selected": "Supprimer la sélection",
    "settings_section_general": "Général",
    "settings_section_scanning": "Analyse",
    "settings_section_selection": "Sélection & suppression",
    "settings_section_rules": "Règles",
    "settings_section_data": "Données & diagnostics",
    "btn_done": "Terminé",
    "btn_restore_defaults": "Restaurer les valeurs par défaut",
    "label_saved": "Enregistré",
    "badge_immediately": "Immédiatement",
    "badge_next_scan": "Dès la prochaine analyse",
    "badge_next_delete": "Dès la prochaine suppression",
    "default_profile_label": "Profil de démarrage d'analyse",
    "default_profile_hint": "Ne modifie pas la sélection actuelle — uniquement le point de départ de la prochaine analyse.",
    "profile_cautious_hint": "Ne coche que ce que le lanceur ne restaurera pas seul : résidus de jeux supprimés, bonus, documentation.",
    "profile_balanced_hint": "La même chose, plus les fichiers de langue hors de votre liste de conservation.",
    "profile_aggressive_hint": "La même chose, plus les composants redistribuables et les résidus d'installation.",
    "profile_custom_hint": "Ne coche rien par catégorie — uniquement les fichiers individuels les plus certains.",
    "confirm_behavior_label": "Demander confirmation avant de supprimer",
    "confirm_yes_label": "Oui",
    "confirm_no_label": "Non",
    "confirm_behavior_hint": "Si désactivé, la suppression démarre immédiatement sans confirmation.",
    "selection_independent_switches_hint": "Ce qui est analysé, ce qui est présélectionné et la méthode de suppression sont trois réglages indépendants.",
    "keep_languages_add_placeholder": "Ajouter une langue…",
    "categories_table_header_category": "Catégorie",
    "categories_table_header_risk": "Risque",
    "categories_table_header_profile_behavior": "Profil par défaut",
    "profile_behavior_auto": "Présélectionné",
    "profile_behavior_manual": "Jamais automatique",
    "disabled_last_keep_language": "Au moins une langue doit rester dans la liste de conservation.",
    "disabled_last_category": "Au moins une catégorie doit rester activée.",
    "disabled_last_library": "Au moins une bibliothèque doit rester incluse dans l'analyse.",
    "keep_english_warning": "Retirer l'anglais ne supprime rien directement. L'analyse suivante proposera les fichiers anglais.",
    "keep_english_absent": "L'anglais n'est pas dans la liste : l'analyse proposera les fichiers de localisation anglais.",
    "btn_keep_english_again": "Conserver à nouveau l'anglais",
    "rules_pack_category_label": "Règles de catégories (rules.json)",
    "rules_pack_lang_label": "Pack de langues (l10n_rules.json)",
    "rules_valid_label": "Valide",
    "rules_invalid_label": "Non valide",
    "db_path_label": "Fichier de base de données :",
    "btn_copy": "Copier",
    "btn_open_folder": "Ouvrir le dossier",
    "danger_zone_label": "ZONE DANGEREUSE",
    "disabled_busy": "Une opération en arrière-plan est en cours",
    "disabled_no_findings": "Analysez d'abord vos bibliothèques",
    "disabled_no_selection": "Rien n'est sélectionné",
    "disabled_export_running": "Un export est déjà en cours",
    "disabled_disclaimer": "Lisez et acceptez d'abord l'avertissement sur l'écran d'accueil",
    "disabled_database": "Impossible d'ouvrir la base de données",
    "profile_label": "Profil :",
    "profile_cautious": "Prudent",
    "profile_balanced": "Équilibré",
    "profile_aggressive": "Agressif",
    "profile_custom": "Personnalisé",
    "profile_hint": "Quels fichiers sont cochés automatiquement. Changer de profil met à jour les cases dans l'arborescence.",
    "plan_filter_label": "Afficher :",
    "plan_filter_all": "toutes les catégories",
    "plan_group_label": "Grouper par :",
    "group_axis_disk": "disque",
    "group_axis_launcher": "lanceur",
    "group_axis_library": "bibliothèque",
    "group_axis_category": "catégorie",
    "group_axis_flat": "aucun",
    "group_unattributed": "Non attribué",
    "btn_remove_category": "Nettoyer toute la catégorie",
    "search_hint": "Rechercher par nom…",
    "btn_clear_search": "Effacer la recherche",
    "search_no_matches": "Aucun résultat ne correspond à la recherche ou au filtre.",
    "elevation_heading": "Accélérer l'analyse ?",
    "elevation_body": "Au moins une bibliothèque se trouve sur un disque dur (HDD). GameTrimmer peut y lire directement la table NTFS ($MFT).",
    "elevation_when_asked": "Refuser prend juste plus de temps : l'analyse parcourt les dossiers et trouve les mêmes fichiers.",
    "btn_continue_without_elevation": "Continuer sans accélération",
    "btn_relaunch_elevated": "Redémarrer en tant qu'administrateur",
    "elevation_never_ask": "Ne plus demander",
    "confirm_delete_heading": "Confirmer la suppression",
    "confirm_label_permanent": "Supprimer définitivement",
    "confirm_label_recycle": "Déplacer vers la corbeille",
    "remember_delete_method": "Mémoriser mon choix",
    "remove_summary_heading": "Résultat de la suppression",
    "btn_close": "Fermer",
    "confirm_clear_heading": "Vider la base de données ?",
    "confirm_clear_body": "Tous les résultats d'analyse et l'historique des opérations seront supprimés définitivement de la base.",
    "btn_confirm_clear": "Vider la base de données",
    "settings_heading": "Paramètres",
    "delete_method_label": "Méthode de suppression :",
    "delete_method_permanent_label": "Suppression définitive (plus rapide)",
    "delete_method_permanent_hint": "Les fichiers sont supprimés sans passer par la corbeille.",
    "delete_method_recycle_label": "Corbeille (plus sûr)",
    "delete_method_recycle_hint": "Les fichiers sont déplacés dans la Corbeille de Windows et peuvent être restaurés.",
    "app_language_label": "Langue de l'application :",
    "lang_name_system": "Suivre la langue de Windows",
    "lang_name_en": "English",
    "lang_name_uk": "Українська",
    "theme_label": "Thème :",
    "theme_system_label": "Suivre le thème de Windows",
    "theme_light_label": "Clair",
    "theme_dark_label": "Sombre",
    "logging_label": "Fichier journal (gametrimmer.log) :",
    "logging_enabled_label": "Activé",
    "logging_disabled_label": "Désactivé",
    "logging_hint": "Enregistre les événements du programme dans le fichier gametrimmer.log à côté de l'exécutable.",
    "btn_open_log_file": "Ouvrir le fichier journal",
    "btn_open_log_folder": "Ouvrir le dossier du journal",
    "disclaimer_heading": "Avant de commencer",
    "disclaimer_body": "GameTrimmer recherche et supprime les fichiers non requis pour lancer vos jeux. Vérifiez toujours avant de supprimer.",
    "disclaimer_accept_label": "Je comprends et j'accepte les conditions",
    "btn_start_scan": "Lancer l'analyse",
    "status_idle": "Prêt",
    "status_scanning": "Analyse en cours…",
    "status_deleting": "Suppression en cours…",
    "status_cancelling": "Annulation en cours…",
    "status_exporting": "Exportation en cours…",
    "empty_libraries_title": "Aucune bibliothèque de jeux trouvée",
    "empty_libraries_body": "Les lanceurs de jeux n'ont pas été détectés automatiquement. Ajoutez des dossiers dans les paramètres.",
    "empty_scan_title": "Aucune analyse effectuée",
    "empty_scan_body": "Cliquez sur « Analyser les bibliothèques » pour trouver les fichiers inutiles et libérer de l'espace.",
    "clean_scan_title": "Tout est propre !",
    "clean_scan_body": "Aucun fichier superflu n'a été trouvé dans vos bibliothèques.",
    "credits_heading": "Remerciements",
    "credits_anthropic": "À l'équipe Claude d'Anthropic pour l'aide au développement.",
    "credits_karpathy": "À Andrej Karpathy pour l'inspiration dans la création d'outils.",
    "credits_tikione": "À l'auteur de TikiOne Steam Cleaner pour l'idée initiale.",
    "scanning_in_progress": "Analyse en cours...",
    "no_findings_hint": "Aucun élément trouvé. Cliquez sur « Analyser les bibliothèques ».",
    "col_language": "Langue",
    "col_files": "Fichiers",
    "col_size": "Taille",
    "col_name": "Nom",
    "col_sort_hint": "Cliquez pour trier par cette colonne.",
    "review_mark_hint": "Vérifiez ce fichier avant de le supprimer.",
    "hover_stub_note": "Remplacé par un micro-stub pour un lancement instantané sans plantage.",
    "ctx_open": "Ouvrir",
    "ctx_reveal_in_explorer": "Afficher dans l'Explorateur",
    "ctx_open_with": "Ouvrir avec…",
    "ctx_copy_path": "Copier le chemin",
    "ctx_never_touch": "Ne jamais toucher ce fichier dans ce jeu",
    "btn_find_standalone": "Trouver les jeux hors lanceurs",
    "find_standalone_hint": "Lit la liste de désinstallation Windows pour les jeux sans lanceur.",
    "standalone_candidates_header": "Installés hors lanceurs — ajoutez ceux qui sont des jeux :",
    "no_standalone_candidates": "Rien trouvé hors de vos lanceurs.",
    "add_library_dialog_title": "Choisir un dossier de bibliothèque",
    "export_dialog_title": "Exporter les résultats d'analyse",
    "text_file_filter_label": "Fichier texte",
    "rules_export_dialog_title": "Choisir un dossier pour exporter les règles",
    "rules_import_dialog_title": "Choisir les fichiers de règles à importer",
    "rules_import_filter_label": "Règles GameTrimmer (JSON)",
    "no_db_path": "Aucun chemin de base de données.",
    "db_path_error": "Erreur lors de la détermination du chemin de la base.",
    "detecting_libraries": "Détection des bibliothèques de jeux...",
    "preparing_database": "Préparation de la base de données...",
    "loading_previous_scan": "Chargement des résultats précédents...",
    "deleting_selected_files": "Suppression des fichiers sélectionnés...",
    "compacting_database": "Compactage de la base de données...",
    "clearing_database": "Vidage de la base de données...",
    "scan_cancelled": "Analyse annulée.",
    "deletion_completed": "Suppression terminée.",
    "database_compacted": "Base de données compactée.",
    "database_cleared": "Base de données vidée.",
    "settings_not_saved_no_path": "Paramètres non enregistrés : chemin introuvable.",
    "verb_analyze": "Analyse",
    "verb_delete": "Suppression",
    "verb_compact": "Compactage de la base",
    "verb_clear": "Vidage de la base",
    "verb_bundle": "Collecte du diagnostic",
    "category_redist": "Packages redistribuables",
    "category_intro": "Vidéos d'intro et logos",
    "category_docs": "Manuels et documentation",
    "category_bonus": "Contenu bonus",
    "category_loc": "Fichiers de langues non utilisées",
    "category_other": "Autres fichiers inutiles",
    "category_orphan": "Restes de jeux désinstallés",
    "orphan_branch_label": "Résidus orphelins",
    "unit_gb": "Go",
    "unit_mb": "Mo",
    "unit_kb": "Ko",
    "unit_b": "o",
    "csv_yes": "oui",
    "csv_no": "non",
    "already_running_title": "GameTrimmer est déjà en cours d'exécution"
}

gld.DICTS["fr"] = fr_dict
print("Registered French dictionary.")
